language: python

# using separate envs with different TOXENVs creates 4x1 Travis build
# matrix, which allows us to clearly distinguish which component under
# test has failed
env:
  matrix:
    - TOXENV=py26
    - TOXENV=py27
    - TOXENV=lint
    - TOXENV=cover


# Only build pushes to the master branch, PRs, and branches beginning with
# `test-`. This reduces the number of simultaneous Travis runs, which speeds
# turnaround time on review since there is a cap of 5 simultaneous runs.
branches:
  only:
    - master
    - /^test-.*$/

sudo: false  # containers
addons:
  apt:
    packages:  # keep in sync with bootstrap/ubuntu.sh and Boulder
    - python
    - python-dev
    - python-virtualenv
    - gcc
    - dialog
    - libssl-dev
    - libffi-dev
    - ca-certificates

install: "travis_retry pip install tox coveralls"
script: 'travis_retry tox'

after_success: '[ "$TOXENV" == "cover" ] && coveralls'

notifications:
  email: false
